name: CD Equipment Loan

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Ejecutar pruebas
        run: ./gradlew test

      - name: Construir proyecto
        run: ./gradlew build

      - name: Publicar JAR como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: equipment-loan-vasconezchristian.jar
          path: build/libs/*.jar